rm -rf ./{build,install}
mkdir build
cd build
cmake -GNinja -DWITH_AQBANKING=OFF -DWITH_SQL=ON -DWITH_PYTHON=ON -DCMAKE_BUILD_TYPE=Debug -DDISABLE_DEPRECATED_GLIB=ON -DDISABLE_DEPRECATED_GTK=OFF -DDISABLE_DEPRECATED_GNOME=ON -DCMAKE_INSTALL_PREFIX=../install ../maint

